#!/usr/bin/env python

import os

# Sketch 49.0
actions = [
    "AddBorder",
    "AddExportFormat",
    "AddFill",
    "AddFlow",
    "AddFlowBack",
    "AddFlowHome",
    "AddInnerShadow",
    "AddShadow",
    "AlignBottom",
    "AlignCenter",
    "AlignJustified",
    "AlignLayersBottom",
    "AlignLayersCenter",
    "AlignLayersLeft",
    "AlignLayersMiddle",
    "AlignLayersRight",
    "AlignLayersTop",
    "AlignLeft",
    "AlignMiddle",
    "AlignRight",
    "AlignTop",
    "AlignmentActions",
    "ApplyFlip",
    "ApplySharedLayerStyle",
    "ApplySharedTextStyle",
    "AssignColorSpace",
    "AutoExpandGroups",
    "BackToInstance",
    "BadgeMenu",
    "BadgeMenu",
    "BaseAlignLayers",
    "BaseStyle",
    "BooleanMenu",
    "BooleanTouchBarGroup",
    "CenterLayersInCanvas",
    "CenterSelectionInVisibleArea",
    "ChangeFlowAnimationFromBottomAnimation",
    "ChangeFlowAnimationFromLeftAnimation",
    "ChangeFlowAnimationFromRightAnimation",
    "ChangeFlowAnimationFromTopAnimation",
    "ChangeFlowAnimationNoAnimation",
    "ChangeFont",
    "ClippingMask",
    "ClippingMaskMode",
    "ClosePath",
    "Cloud",
    "CollapseAllGroups",
    "ColorInspectorCircularGradientTab",
    "ColorInspectorColorTab",
    "ColorInspectorImageTab",
    "ColorInspectorLinearGradientTab",
    "ColorInspectorModeBorderTouchBarGroup",
    "ColorInspectorModeFillTouchBarGroup",
    "ColorInspectorModePicker",
    "ColorInspectorRadialGradientTab",
    "ConstraintFixHeight",
    "ConstraintFixWidth",
    "ConstraintPinBottom",
    "ConstraintPinLeft",
    "ConstraintPinRight",
    "ConstraintPinTop",
    "ConstraintReset",
    "ConvertColorSpace",
    "ConvertFlowToHotspot",
    "ConvertSymbolOrDetachInstances",
    "ConvertToOutlines",
    "Copy",
    "CopyCSSAttributes",
    "CopySVGCode",
    "CopyStyle",
    "CreateSharedStyle",
    "CreateSymbol",
    "CurveModeAsymmetric",
    "CurveModeDisconnected",
    "CurveModeMirrored",
    "CurveModeStraight",
    "CurveModeTouchGroup",
    "Cut",
    "Data",
    "DefaultStyle",
    "Delete",
    "DetachSharedStyle",
    "Difference",
    "DistributeActions",
    "DistributeHorizontally",
    "DistributeVertically",
    "Duplicate",
    "Edit",
    "EditColorSpace",
    "Export",
    "ExportPDFBook",
    "ExportSelectionWithExportFormats",
    "FindLayer",
    "Flatten",
    "FlattenSelection",
    "FlipHorizontal",
    "FlipVertical",
    "FollowFlow",
    "GridSettings",
    "Group",
    "HideAllGridsAndLayouts",
    "HideLayer",
    "IgnoreClippingMask",
    "ImageOriginalSize",
    "IncompatiblePluginsDisabled",
    "InsertArrow",
    "InsertArtboard",
    "InsertHotspot",
    "InsertImage",
    "InsertLine",
    "InsertMenu",
    "InsertSharedText",
    "InsertSlice",
    "InsertSymbol",
    "InsertTextLayer",
    "InsertVector",
    "Intersect",
    "Join",
    "LayerFocusActions",
    "LayerHeightFocus",
    "LayerWidthFocus",
    "LayerXFocus",
    "LayerYFocus",
    "LayoutSettings",
    "LicenseExpired",
    "LockLayer",
    "Magnifier",
    "MakeGrid",
    "MakeLowercase",
    "MakeUppercase",
    "ManageForeignSymbol",
    "ManageLayerStyles",
    "ManageTextStyles",
    "MaskWithShape",
    "Mirror",
    "MoveBackward",
    "MoveForward",
    "MoveToBack",
    "MoveToFront",
    "MoveToTop",
    "MoveUpHierarchy",
    "NewPage",
    "NextPage",
    "OpenPreview",
    "OvalShape",
    "Paste",
    "PasteHere",
    "PasteOverSelection",
    "PasteStyle",
    "Pencil",
    "PolygonShape",
    "PreviewAtActualSize",
    "PreviousPage",
    "Print",
    "RectangleShape",
    "Redo",
    "ReduceFileSize",
    "ReduceImageSize",
    "RemoveFlow",
    "RemoveTextTransform",
    "RemoveUnusedStyles",
    "RenameLayer",
    "ReplaceColor",
    "ReplaceFonts",
    "ReplaceImage",
    "ReplaceWithSymbol",
    "ResetBoolean",
    "ResetSharedStyle",
    "ResetSymbolSize",
    "ResizeArtboardToFit",
    "RevealInLayerList",
    "ReversePath",
    "Rotate",
    "RotateClockwise",
    "RotateCounterclockwise",
    "RoundToPixel",
    "RoundedRectangleShape",
    "SaveAsTemplate",
    "Scale",
    "Scissors",
    "SelectAll",
    "SelectAllArtboards",
    "SendToSymbolsPage",
    "Shape",
    "ShowBorderOptions",
    "ShowFillOptions",
    "ShowReplaceColorSheet",
    "SmartRotate",
    "SpiralShape",
    "Split",
    "StarShape",
    "Subtract",
    "SyncLibrary",
    "SyncSharedStyle",
    "TextAlignTouchBarGroup",
    "TextOnPath",
    "TextStyleTouchBar",
    "ToggleAlignmentGuides",
    "ToggleArtboardShadow",
    "ToggleBorder",
    "ToggleFill",
    "ToggleFlowInteraction",
    "ToggleGrid",
    "ToggleInspectorVisibility",
    "ToggleInterface",
    "ToggleLayerHighlight",
    "ToggleLayerListVisibility",
    "ToggleLayout",
    "TogglePixelGrid",
    "TogglePixelLines",
    "ToggleRulers",
    "ToggleSelection",
    "ToggleSliceInteraction",
    "ToggleToolbarVisibility",
    "ToolsMenu",
    "Transform",
    "TriangleShape",
    "Underline",
    "Undo",
    "Ungroup",
    "Union",
    "UpdatePlugins",
    "ViewMenu",
    "Zoom",
    "ZoomActions",
    "ZoomIn",
    "ZoomOut",
    "ZoomToActualSize",
    "ZoomToSelection"
]

documentedActions = [
    "AddAsLibrary",
    "ArtboardChanged",
    "ExportSlices",
    "SelectionChanged"
]

fakeActions = [
    "CloseDocument",
    "DocumentSaved",
    "HandlerGotFocus",
    "HandlerLostFocus",
    "HandleURL",
    "LayersMoved",
    "OpenDocument",
    "RunPluginCommand",
    "TextChanged"
]

allActions = actions + fakeActions

actionsPath = "_actions"
if not os.path.exists(actionsPath):
    os.mkdir(actionsPath)

for action in allActions:
    with open(os.path.join(actionsPath, action +".md"), "w") as f:
        template = """---
title: {actionName}
trigger: TBD
documented: false
---

The `{actionName}` action is triggered when…

## Action Context

This action receives the [default context](/guides/action-api/#default-action-context).

## Examples

No examples yet.
"""

        f.write(template.format(actionName=action))
